name: "Push Notification"
on: push

jobs:
  test:
  if: github.repository == 'PCBox/PCBox'
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#pcbox"
          server: "irc.libera.chat"
          nickname: pcbox-github
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}